format_version: v1.0
type: UniqueComponent
attributes: {id: supc}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: SUPC_VREF_SEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '6'}
  - type: Boolean
    attributes: {id: SUPC_VREF_TSEN}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: SUPC_VREF_VREFOE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '23', y: '239', id: supc}
