format_version: v1.0
type: UniqueComponent
attributes: {id: dac}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: DAC_CHANNEL_0_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: DAC_CHANNEL_0_REFRESH}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: DAC_CHANNEL_0_SPEED}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Boolean
    attributes: {id: DAC_CHANNEL_1_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: KeyValueSet
    attributes: {id: DAC_CHANNEL_1_REFRESH}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: DAC_CHANNEL_1_SPEED}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: KeyValueSet
    attributes: {id: DAC_DATA_ADJUSTMENT0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: KeyValueSet
    attributes: {id: DAC_DATA_ADJUSTMENT1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: KeyValueSet
    attributes: {id: DAC_OPERATING_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: KeyValueSet
    attributes: {id: DAC_REFSEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '3'}
- type: ElementPosition
  attributes: {x: '30', y: '100', id: dac}
