configName: sam_e54_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAME54P20A
projectName: ''
settings:
  PackageFilter: csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.5.1
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.0.30\atdf\ATSAME54P20A.atdf
