format_version: v1.0
type: UniqueComponent
attributes: {id: pm}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: PM_BKUPCFG_BRAMCFG}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: KeyValueSet
    attributes: {id: PM_HIBCFG_BRAMCFG}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: KeyValueSet
    attributes: {id: PM_HIBCFG_RAMCFG}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: KeyValueSet
    attributes: {id: PM_STDBYCFG_FASTWKUP}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: PM_STDBYCFG_RAMCFG}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
- type: ElementPosition
  attributes: {x: '334', y: '103', id: pm}
